platform :ios, '11.0'

target 'AplikacjaRekrutacyjna' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Pods for AplikacjaRekrutacyjna
	pod 'SDWebImage'

end
